<?php
namespace backend\models;
use common\models\SignupForm;
use common\models\User;
/**
 * Signup form
 */
class RegisterForm extends SignupForm
{
    public $username;
    public $email;
    public $password;
    /**
     * @return array
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
    /**
     * Signs user up.
     *
     * @return User|null the saved model or null if saving fails
     */
    public function signup()
    {
        return parent::signup(); // TODO: Change the autogenerated stub
    }
}